//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garvan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garvan.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the site.
        /// </summary>
        public static string AboutTheSite {
            get {
                return ResourceManager.GetString("AboutTheSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gaming world will be enhanced through our beautiful designed products. The first step towards improving the gaming experience is to remove the Cable Monster out of your desk!.
        /// </summary>
        public static string AboutUsInfo {
            get {
                return ResourceManager.GetString("AboutUsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything we do, we believe in better gaming world..
        /// </summary>
        public static string AboutUsSubHeader {
            get {
                return ResourceManager.GetString("AboutUsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because it’s &lt;b&gt;Your World!&lt;/b&gt;.
        /// </summary>
        public static string AboutUsSubInfo {
            get {
                return ResourceManager.GetString("AboutUsSubInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And don&apos;t miss cool new products and special offers.
        /// </summary>
        public static string AndDontMissCoolNewProductsAndSpecialOffers {
            get {
                return ResourceManager.GetString("AndDontMissCoolNewProductsAndSpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask us anything by mail, phone call or direct message..
        /// </summary>
        public static string AskUsAnything {
            get {
                return ResourceManager.GetString("AskUsAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garvan Entertainment. All rights reserved..
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already registered.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail was successfully registered.&lt;br/&gt;Stay tuned for more news from Garvan.
        /// </summary>
        public static string EmailSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("EmailSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request: The request cannot be fulfilled due to bad syntax.
        /// </summary>
        public static string Error400 {
            get {
                return ResourceManager.GetString("Error400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Error403 {
            get {
                return ResourceManager.GetString("Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, this page was not found.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timed out waiting for the request.
        /// </summary>
        public static string Error408 {
            get {
                return ResourceManager.GetString("Error408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error - server was unable to finish processing the request.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred. Please try again.
        /// </summary>
        public static string ErrorOccurredTryAgain {
            get {
                return ResourceManager.GetString("ErrorOccurredTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That’s odd... Something we didn&apos;t expect happened.
        /// </summary>
        public static string ErrorOther {
            get {
                return ResourceManager.GetString("ErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming case-desks and accessories.
        /// </summary>
        public static string GamingCaseDesksAndAccessories {
            get {
                return ResourceManager.GetString("GamingCaseDesksAndAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garvan.
        /// </summary>
        public static string Garvan {
            get {
                return ResourceManager.GetString("Garvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garvan Entertainment.
        /// </summary>
        public static string GarvanEntertainment {
            get {
                return ResourceManager.GetString("GarvanEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@garvanentertainment.com.
        /// </summary>
        public static string GarvanMail {
            get {
                return ResourceManager.GetString("GarvanMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +359 88 732 1987.
        /// </summary>
        public static string GarvanPhone {
            get {
                return ResourceManager.GetString("GarvanPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +359887321987.
        /// </summary>
        public static string GarvanPhoneWithoutSpaces {
            get {
                return ResourceManager.GetString("GarvanPhoneWithoutSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want your name here,.
        /// </summary>
        public static string IfYouWantYourNameHere {
            get {
                return ResourceManager.GetString("IfYouWantYourNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha entered. Please try again..
        /// </summary>
        public static string InvalidCaptchaEntered {
            get {
                return ResourceManager.GetString("InvalidCaptchaEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s &lt;b&gt;your&lt;/b&gt; world.
        /// </summary>
        public static string ItsYourWorld {
            get {
                return ResourceManager.GetString("ItsYourWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent. We will contact you shortly.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next chapter.
        /// </summary>
        public static string NextChapter {
            get {
                return ResourceManager.GetString("NextChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our distributors.
        /// </summary>
        public static string OurDistributors {
            get {
                return ResourceManager.GetString("OurDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid e-mail address.
        /// </summary>
        public static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        public static string PleaseFillAllFields {
            get {
                return ResourceManager.GetString("PleaseFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the full story.
        /// </summary>
        public static string ReadTheFullStory {
            get {
                return ResourceManager.GetString("ReadTheFullStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop now.
        /// </summary>
        public static string ShopNow {
            get {
                return ResourceManager.GetString("ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened. Please try again.
        /// </summary>
        public static string SomethingHappenedTryAgain {
            get {
                return ResourceManager.GetString("SomethingHappenedTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SpecificationsColorLabel {
            get {
                return ResourceManager.GetString("SpecificationsColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string SpecificationsColorValue {
            get {
                return ResourceManager.GetString("SpecificationsColorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string SpecificationsDimensionsLabel {
            get {
                return ResourceManager.GetString("SpecificationsDimensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1600x675x800 mm (63x26.6x31.5 in) (W x D x H).
        /// </summary>
        public static string SpecificationsDimensionsValue {
            get {
                return ResourceManager.GetString("SpecificationsDimensionsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Slots.
        /// </summary>
        public static string SpecificationsExpansionSlotsLabel {
            get {
                return ResourceManager.GetString("SpecificationsExpansionSlotsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string SpecificationsExpansionSlotsValue {
            get {
                return ResourceManager.GetString("SpecificationsExpansionSlotsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form-Factor.
        /// </summary>
        public static string SpecificationsFormFactorLabel {
            get {
                return ResourceManager.GetString("SpecificationsFormFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini-ITX, Micro-ATX, ATX.
        /// </summary>
        public static string SpecificationsFormFactorValue {
            get {
                return ResourceManager.GetString("SpecificationsFormFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front I/O.
        /// </summary>
        public static string SpecificationsFrontIOLabel {
            get {
                return ResourceManager.GetString("SpecificationsFrontIOLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2xUSB3.0, Mic, Headphone, On/Off.
        /// </summary>
        public static string SpecificationsFrontIOValue {
            get {
                return ResourceManager.GetString("SpecificationsFrontIOValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string SpecificationsMaterialLabel {
            get {
                return ResourceManager.GetString("SpecificationsMaterialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal frame. Anodized aluminum (panel), tempered glass (tabletop).
        /// </summary>
        public static string SpecificationsMaterialValue {
            get {
                return ResourceManager.GetString("SpecificationsMaterialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. CPU Cooler Height.
        /// </summary>
        public static string SpecificationsMaxCpuCoolerHeightLabel {
            get {
                return ResourceManager.GetString("SpecificationsMaxCpuCoolerHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 mm (7.08&quot;).
        /// </summary>
        public static string SpecificationsMaxCpuCoolerHeightValue {
            get {
                return ResourceManager.GetString("SpecificationsMaxCpuCoolerHeightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. GPU Length.
        /// </summary>
        public static string SpecificationsMaxGpuLengthLabel {
            get {
                return ResourceManager.GetString("SpecificationsMaxGpuLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 mm (12.6in).
        /// </summary>
        public static string SpecificationsMaxGpuLengthValue {
            get {
                return ResourceManager.GetString("SpecificationsMaxGpuLengthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Load.
        /// </summary>
        public static string SpecificationsMaxLoadLabel {
            get {
                return ResourceManager.GetString("SpecificationsMaxLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 kg (440lb).
        /// </summary>
        public static string SpecificationsMaxLoadValue {
            get {
                return ResourceManager.GetString("SpecificationsMaxLoadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Supply.
        /// </summary>
        public static string SpecificationsPowerSupplyLabel {
            get {
                return ResourceManager.GetString("SpecificationsPowerSupplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard ATX.
        /// </summary>
        public static string SpecificationsPowerSupplyValue {
            get {
                return ResourceManager.GetString("SpecificationsPowerSupplyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What makes the magic?.
        /// </summary>
        public static string SpecificationsSubHeader {
            get {
                return ResourceManager.GetString("SpecificationsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string SpecificationsWeightLabel {
            get {
                return ResourceManager.GetString("SpecificationsWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approx. 60 kg (132lbs).
        /// </summary>
        public static string SpecificationsWeightValue {
            get {
                return ResourceManager.GetString("SpecificationsWeightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 1.
        /// </summary>
        public static string StoryChapter1Header {
            get {
                return ResourceManager.GetString("StoryChapter1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another day has passed. Her only wish was just to sit and play his favorite game, relaxing from the hard day. However, after an hour, her eyes got heavier and heavier. In one moment, she felt a creepy chill, as if someone is watching her, waiting to make a move..
        /// </summary>
        public static string StoryChapter1Paragraph1 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything slowly became darker, as she stared into the void a growing shadow got more recognizable. Those sinister eyes paralyzed her until she could not move a muscle, as if something was wrapping her into a deadly cocoon, like a venomous spider preparing to feed on its pray. But it was no spider, may be something far more worse... She was asleep and did not feel anything..
        /// </summary>
        public static string StoryChapter1Paragraph2 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His servants were arranged during the day and waited for his victim. The victim was sleeping and they easily conquer her. Every move that she made tided up the grip harder and harder around her body. In the final moment, when she was just about to give up her final breath, a hand reached towards her, as last light of hope..
        /// </summary>
        public static string StoryChapter1Paragraph3 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown voice: - RISE UP.
        /// </summary>
        public static string StoryChapter1Paragraph4 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strange but also a strong feeling that she can rely on this hand went through her entire body..
        /// </summary>
        public static string StoryChapter1Paragraph5 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His reign was threatened..
        /// </summary>
        public static string StoryChapter1Paragraph6 {
            get {
                return ResourceManager.GetString("StoryChapter1Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 2.
        /// </summary>
        public static string StoryChapter2Header {
            get {
                return ResourceManager.GetString("StoryChapter2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another day has passed. Her only wish was just to sit and play his favorite game, relaxing from the hard day. However, after an hour, her eyes got heavier and heavier. In one moment, she felt a creepy chill, as if someone is watching her, waiting to make a move..
        /// </summary>
        public static string StoryChapter2Paragraph1 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything slowly became darker, as she stared into the void a growing shadow got more recognizable. Those sinister eyes paralyzed her until she could not move a muscle, as if something was wrapping her into a deadly cocoon, like a venomous spider preparing to feed on its pray. But it was no spider, may be something far more worse... She was asleep and did not feel anything..
        /// </summary>
        public static string StoryChapter2Paragraph2 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His servants were arranged during the day and waited for his victim. The victim was sleeping and they easily conquer her. Every move that she made tided up the grip harder and harder around her body. In the final moment, when she was just about to give up her final breath, a hand reached towards her, as last light of hope..
        /// </summary>
        public static string StoryChapter2Paragraph3 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown voice: - RISE UP.
        /// </summary>
        public static string StoryChapter2Paragraph4 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strange but also a strong feeling that she can rely on this hand went through her entire body..
        /// </summary>
        public static string StoryChapter2Paragraph5 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His reign was threatened..
        /// </summary>
        public static string StoryChapter2Paragraph6 {
            get {
                return ResourceManager.GetString("StoryChapter2Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 3.
        /// </summary>
        public static string StoryChapter3Header {
            get {
                return ResourceManager.GetString("StoryChapter3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another day has passed. Her only wish was just to sit and play his favorite game, relaxing from the hard day. However, after an hour, her eyes got heavier and heavier. In one moment, she felt a creepy chill, as if someone is watching her, waiting to make a move..
        /// </summary>
        public static string StoryChapter3Paragraph1 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything slowly became darker, as she stared into the void a growing shadow got more recognizable. Those sinister eyes paralyzed her until she could not move a muscle, as if something was wrapping her into a deadly cocoon, like a venomous spider preparing to feed on its pray. But it was no spider, may be something far more worse... She was asleep and did not feel anything..
        /// </summary>
        public static string StoryChapter3Paragraph2 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His servants were arranged during the day and waited for his victim. The victim was sleeping and they easily conquer her. Every move that she made tided up the grip harder and harder around her body. In the final moment, when she was just about to give up her final breath, a hand reached towards her, as last light of hope..
        /// </summary>
        public static string StoryChapter3Paragraph3 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown voice: - RISE UP.
        /// </summary>
        public static string StoryChapter3Paragraph4 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strange but also a strong feeling that she can rely on this hand went through her entire body..
        /// </summary>
        public static string StoryChapter3Paragraph5 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His reign was threatened..
        /// </summary>
        public static string StoryChapter3Paragraph6 {
            get {
                return ResourceManager.GetString("StoryChapter3Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cable Monster (Prelude).
        /// </summary>
        public static string StoryPreludeHeader {
            get {
                return ResourceManager.GetString("StoryPreludeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hundred years ago, he was only an idea. A beautiful idea and people believed in him. They used him with no questions and no doubt. In exchange he takes what he wants. As a plague cell, he wants only one thing, to grow and consume space and thus, create a place for its minions..
        /// </summary>
        public static string StoryPreludeParagraph1 {
            get {
                return ResourceManager.GetString("StoryPreludeParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s how he managed to get to the home of each one of them. Sometimes people clean the bodies of a dead minions, but they never faced the real threat. He was smart and deadly..
        /// </summary>
        public static string StoryPreludeParagraph2 {
            get {
                return ResourceManager.GetString("StoryPreludeParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very few manage to resist him..
        /// </summary>
        public static string StoryPreludeParagraph3 {
            get {
                return ResourceManager.GetString("StoryPreludeParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address....
        /// </summary>
        public static string SubscribePlaceholder {
            get {
                return ResourceManager.GetString("SubscribePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to our newsletter.
        /// </summary>
        public static string SubscribeToOurNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToOurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cable monster.
        /// </summary>
        public static string TheCableMonster {
            get {
                return ResourceManager.GetString("TheCableMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write us.
        /// </summary>
        public static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
    }
}
